# Site settings
title: Root314
header-img: img/home-bg.jpg
email: hello@root314.com
copyright_name: Root314
description: "Software Defined Engineer - Cloud, OpenStack, Network"
baseurl: ""
#url: "http://yourdomain.com"
twitter:
  username: Miouge
github_username:  Miouge1
linkedin_username:  maximeguyot
#facebook_username:  StartBootstrap
email_username:  hello@root314.com
timezone: Europe/Brussels

collections:
  slides:
  presentations:
    output: true
  trainings:
    output: true

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","reveal.js/node_modules","reveal.js/test","reveal.js/examples","reveal.js/plugin/markdown/","reveal.js/css/theme/README.md"]

gems: [jekyll-paginate, jekyll-feed, jekyll-seo-tag, jekyll-sitemap, jekyll-redirect-from]
